version: '3'

services:
  socket-be:
    build: 
      context: socket-be
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  main-be1:
    build: 
      context: load-balancer
      dockerfile: Dockerfile
    environment:
      - PORT=4012

  main-be2:
    build: 
      context: load-balancer
      dockerfile: Dockerfile
    environment:
      - PORT=4013

  main-be3:
    build: 
      context: load-balancer
      dockerfile: Dockerfile
    environment:
      - PORT=4014

  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - main-be1
      - main-be2
      - main-be3

  frontend:
    build: 
      context: Project-Management-App
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BASE_URL=http://192.168.1.9:8080
      - REACT_APP_SOCKET_URL=http://192.168.1.9:4000
    ports:
      - "3000:3000"
    depends_on:
      - load-balancer
      - socket-be